Add flow
conveyal/browsochrones pull request #88
Opened 2017-04-26 23:09 UTC by trevorgerhardt

Also, quite a bit of refactoring around the insanity of `get-transitive-data` 😅

2017-04-27 02:02 UTC, mattwigway reviewed
Changes mostly look good, a few questions, and I will need to review the refactor of the pathfinding code when I have a bit more time at my disposal.

2017-04-27 02:02 UTC, mattwigway commented on lib/get-transitive-data.js
> +  transitiveNetwork: any
Should we at least define a TransitiveNetwork type that has all the top level members (journeys, etc) as type any so it at least prevents you from accidentally passing in totally the wrong type of object?

2017-04-27 02:02 UTC, mattwigway commented on lib/get-transitive-data.js
> +    // log a javascript error than crash the tab (??)
i.e. we don't want to have this throw a 'cannot read property whatever of undefined' when it tries to read a property of the (null) path.

2017-04-27 02:02 UTC, mattwigway commented on lib/get-transitive-data.js
> +  let allStopPatternStopSets = pathCounts
I'm not clear what a StopPatternStopSet is.

2017-04-27 02:02 UTC, mattwigway commented on lib/get-transitive-data.js
>    for (const j1 of c1) {
Ugh. Who wrote code with variables like this 🙈  (it was me). I'll refactor next week.

2017-04-27 02:02 UTC, mattwigway commented on lib/get-transitive-data.js
> +  if (!pat1 || !pat2) return Infinity
What's the impetus for adding this?

2017-04-27 02:02 UTC, mattwigway commented on lib/types.js
> +  x: number,
Is there a way to restrict this to integers?

2017-04-27 02:02 UTC, mattwigway commented on lib/types.js
> +  x: number,
Same comment about restricting to integers.

2017-04-27 02:02 UTC, mattwigway commented on lib/types.js
> +  height: number,
Same comment about integers for all of these.

2017-04-27 13:28 UTC, trevorgerhardt commented on lib/get-transitive-data.js
> +  transitiveNetwork: any
👌

2017-04-27 13:34 UTC, trevorgerhardt commented on lib/get-transitive-data.js
> +  if (!pat1 || !pat2) return Infinity
`find` can return `undefined` and `flow` won't let you call a method on a possibly `undefined` value

2017-04-27 13:36 UTC, trevorgerhardt commented on lib/types.js
> +  x: number,
I don't believe so as that would be a runtime constraint on the value contained in a JavaScript Number. Google `flowtype integers` and let me know if you see anything promising. Remember I'm only a few days ahead on `flow`y things 😉

2017-04-27 13:37 UTC, trevorgerhardt commented on lib/get-transitive-data.js
> +  let allStopPatternStopSets = pathCounts
So we go from `PathDescriptor`s which are `[stopId, pathId]` to `StopPatternStop`s which are `[stop, pattern, stop]` and when we accumulate them by segment I call that a set 😉 

...naming things, open to suggestions! 😬

2017-04-27 13:38 UTC, trevorgerhardt commented on lib/get-transitive-data.js
> +  let allStopPatternStopSets = pathCounts
Also, these `types` will hopefully turn into things we can reuse across projects so it's a good time to debate how we should represent this kind of data!

2017-04-28 01:35 UTC, evansiroky commented on lib/generate-destination-data.js
> +  log: Function,
[The Function type is unsafe and should be avoided](https://flow.org/en/docs/types/functions/#toc-function-type).

2017-04-28 01:39 UTC, evansiroky commented on lib/index.js
> +  log (...args: any[]) {
I'm cool w/ the `any` type in this case.

2017-04-28 01:39 UTC, evansiroky commented on lib/index.js
> +    done: Function
[The Function type is unsafe and should be avoided](https://flow.org/en/docs/types/functions/#toc-function-type).

2017-04-28 01:41 UTC, evansiroky commented on lib/isochrone-tile.js
> +  colorScheme: Function,
[The Function type is unsafe and should be avoided](https://flow.org/en/docs/types/functions/#toc-function-type).

2017-04-28 01:42 UTC, evansiroky commented on lib/origin.js
> +  log: Function,
I'll allow this one.  ;)

2017-04-28 01:43 UTC, evansiroky commented on lib/propagation.js
> +  next: Function,
[The Function type is unsafe and should be avoided](https://flow.org/en/docs/types/functions/#toc-function-type).

2017-04-28 01:44 UTC, evansiroky commented on lib/types.js
> +  contains: Function,
[The Function type is unsafe and should be avoided](https://flow.org/en/docs/types/functions/#toc-function-type).

2017-04-28 01:46 UTC, evansiroky commented on lib/types.js
> +  routes: any[],
Try to avoid `any` whenever possible.

2017-04-28 01:48 UTC, evansiroky requested changes
Let's try to not use wildcard types like Function, Object, any or mixed.

2017-05-01 18:48 UTC, trevorgerhardt commented
@evansiroky & @mattwigway changes are ready for another look 👌

2017-05-01 18:53 UTC, trevorgerhardt commented
@evansiroky I left `Function` in instances where `log` is being passed around.

2017-05-01 19:14 UTC, evansiroky commented on lib/types.js
> +  stop_id: number,
I think this should be a string type

2017-05-01 19:14 UTC, evansiroky commented on lib/types.js
> +  route_id: number,
I think these should also be a string type

2017-05-01 19:17 UTC, evansiroky approved these changes
Flow type stuff looks good to me once those `id` fields are changed to string.  Can't give a good comment on all the logic inside.

2017-05-01 19:40 UTC, merged